[phases.setup]
nixPkgs = ["nodejs-22_x", "pnpm"]

[phases.install]
cmds = [
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  "cd apps/server && pnpm build"
]

[start]
cmd = "cd apps/server && pnpm start"
